title: Your awesome title
email: your-email@example.com
description: Argle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jadudm
github_username:  jadudm

# Build settings
theme: uswds-jekyll
plugins:
  - jekyll-feed
scripts:
    - "/assets/uswds/js/uswds.min.js"
    - "https://d3js.org/d3.v6.min.js"
    - "https://unpkg.com/d3-simple-slider"
    - "https://cdn.jsdelivr.net/npm/chart.js@2.8.0"
    - "js/global.js"
    - "js/model.js"
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
